New inv
waylaidwanderer/SteamTradeOffersBot pull request #23
Opened 2017-08-15 22:21 UTC by Zexuz

2017-08-16 02:53 UTC, waylaidwanderer commented
I'd rather you replace the old GenericInventory class instead, but use it as a base-line for implementation/code-style.

2017-08-16 10:38 UTC, Zexuz commented
So replace the old inventory class with my new one and tighty up the code?

This will mean that all `FetchInventory` (`http://api.steampowered.com/IEconItems_<appid>/GetPlayerItems/`) will get removed and that 

`Inventory GetInventory` will be the only way to fetch inventories?

2017-08-16 19:37 UTC, Zexuz commented
*Facepalm*... I don't know what I was doing last night.
I now see that you have a class named GenericInventory and that I was looking at the wrong Inventory.

I will fix this PR ASAP.

2017-08-16 23:22 UTC, waylaidwanderer commented
>I now see that you have a class named GenericInventory and that I was looking at the wrong Inventory.

That's correct. I meant you should update this class to use the new endpoint for your pull request.

2017-08-17 20:30 UTC, Zexuz commented
The GenericInventory.cs now uses the new api for fetching players inventories.

Most of the things is the same.
Some of the changes are
* The Item class
* The ItemDescription class
* The inventory class now only have two methods. `Item GetItem(ItemDescription itemDescription)` and `ItemDescription GetItemDescription(Item item)`
* The constructor now takes a extra parameter `bool onlyTradeableItems`. Set this to true and we only fetch items that has the flag trade-able set to true

### Usage example
```csharp
var bot = StartAndConfigBot();

var inventory = new GenericInventory(new SteamID(76561198077954112), bot.SteamWeb, new Dictionary<int, int>
{
    {730, 2},
    {(int) GenericInventory.AppId.PUBG, (int) GenericInventory.ContextId.PUBG},
}, true);

inventory.InventoriesLoaded += (sender, args1) =>
{
    var inv = sender as GenericInventory;
    Console.WriteLine($"success : {inv.Success}");
    Console.WriteLine($"Inventories loaded: {string.Join(",",inv.Inventories.Keys)}"); // prints: Inventories loaded: 578080,730
};

var csInv = inventory.Inventories[730][2];

```

I also believe that `AddForeignInventory` and `FetchForeignInventory` should be removed and if you want to fetch another persons inventory, create a new GenericInventory instance.

2017-08-18 05:15 UTC, waylaidwanderer commented
Pull request looks great. Left some code review comments if you wanna take a look.

2017-08-18 12:37 UTC, Zexuz commented on SteamAPI/GenericInventory.cs
>          /// </summary>
Test

2017-08-18 12:38 UTC, Zexuz commented
How/where can I see these "comments"? Never used this feature before.

2017-08-18 19:43 UTC, waylaidwanderer commented
You'll probably have to visit the desktop version of GitHub.

2017-08-18 20:58 UTC, waylaidwanderer commented on SteamAPI/GenericInventory.cs
> +            var inventory = FetchForeignInventory(steamId, appId, contextId,onlyTradeableItems);
Could you add a space here?

2017-08-18 20:58 UTC, waylaidwanderer commented on SteamAPI/GenericInventory.cs
> -        private Inventory FetchInventory(string inventoryUrl, SteamID steamId, int appId, ulong contextId, int start = 0)
You should implement the `count` and `after_assetid` parameters instead, since `start` was removed:

`http://steamcommunity.com/inventory/76561198045552709/570/2?l=english&count=250&start_assetid=8244114748`

Maybe an option to change the language too?

2017-08-18 22:33 UTC, Zexuz commented
In your inventory. (look at this link http://steamcommunity.com/inventory/76561198045552709/570/2?l=english&count=5000 in browser)

you have two items with "classid":"848466467","instanceid":"1507031039", diffrent AssetId but same classId and instanceid. Is this a bug on steams end? I was told that instaceid + classid was unique.

this code breaks beacuse of it

```csharp
 public ItemDescription GetItemDescription(Item item)
            {
                if (item == null) return null;

                return Descriptions.SingleOrDefault(itemDesc =>
                    itemDesc.AppId.ToString() == item.Appid &&
                    itemDesc.ClassId.ToString() == item.ClassId &&
                    itemDesc.InstanceId.ToString() == item.InstanceId
                );
            }
```

since they refer to the same `ItemDescription` i will change the `SingelOrDefault` to `FirstOrDefault`.

That said, this seams like a bug to me.

2017-08-18 23:18 UTC, waylaidwanderer commented
Only assetid is unique.

2017-08-18 23:38 UTC, Zexuz commented
Okej, well. The new code will fix that also. Since both Assets are referring to the same ItemDescription.

If there is no more problems, this should be good to be merged in.

2017-08-18 23:46 UTC, waylaidwanderer requested changes

2017-08-18 23:46 UTC, waylaidwanderer commented on SteamAPI/GenericInventory.cs
> +                inventoryUrl += "?trading=1";
This would probably break the url. Also I'm not sure if `trading=1` actually does anything with the new endpoint.

2017-08-18 23:53 UTC, Zexuz commented on SteamAPI/GenericInventory.cs
> +                inventoryUrl += "?trading=1";
Yee, just tested `?trading=1/0`, did not do anything so I will remove it and fix the `?` in the url Query.

2017-08-19 00:26 UTC, waylaidwanderer approved these changes

2017-08-19 00:28 UTC, waylaidwanderer commented
@Zexuz there is one way you can implement `tradableOnly` - the items descriptions have a `tradable` property. You could perhaps filter out anything with `tradable: 0` if `tradableOnly` is set to `true`?

2017-08-19 00:34 UTC, Zexuz commented
Yes, but then we already have made the http call. My plan was to save time and space in the HTTP call.
Now the end user can filter those out by them self.
Kinda how then need to pair Item with ItemDescription. All they have to do is `inv.Item.where(item => item.tradeableOnly == true)`. Just my 2 cents

2017-08-19 00:36 UTC, waylaidwanderer commented
Yeah I mean it's not really a big deal, just a "nice-to-have" kind of thing.

2017-08-19 00:40 UTC, Zexuz commented
Okey, I hear you. I might do it in the feature, but then I will create a new PR and implement some other nice things.

2017-08-19 02:23 UTC, merged

2017-08-19 02:24 UTC, waylaidwanderer commented
Thanks, merged.